@startuml

Title Diagrama: Escuela y Asignaciones

class Escuela{
	 -int CANTIDAD_ASIGNACIONES_DEFAULT
	 -String nombreEscuela
	 -Asignacion[] asignaciones
	 	 
	 +agregarAsignacion()
	 +mostrarAsignaciones()
}


class Asignacion{
	 -Materia materia
	 -Alumno alumno
	 -Nota[] notas

	 +asignarNota()
	 +calcularPromedio()
	 +estadoMateria()
	 +mostrarNotas()
}

class Nota{
	-Double valorNota
	-String tipoNota
	
	+mostrarValorNota
	+mostrarNotas
}


class Alumno{
	-String nombre
	-int edad
	
	+mostrarAlumno()
}


class Materia{
	-String nombreMateria
	-String cuantrimestre
	
	+mostrarMateria()
}


Escuela "1" --> "*" Asignacion : Tiene muchas
Asignacion "*" -right-> "1" Materia : Tiene una
Asignacion "*" -left-> "1" Alumno : Tiene uno
Asignacion "1" --> "*" Nota : Tiene muchas
Nota "*" -right-> "1" Materia : Pertenece a




@enduml